#include "Utils.h"

#define TRUE 1
#define FALSE 0
#define SUCESSO_CADASTRO -1
#define ERRO_CADASTRO_MATRICULA -2
#define ERRO_CADASTRO_SEXO -3
#define ERRO_DATA_INVALIDA -4
#define LISTA_VAZIA -5
#define SUCESSO_EXCLUSAO -6
#define NAO_ENCONTRADO -7
#define ERRO_CADASTRO_SEMESTRE -8
#define ERRO_CADASTRO_PROFESSOR -9
#define SUCESSO_MATRICULA -10
#define ERRO_CADASTRO_ALUNO -11